---

- name: Determine the running kernel release
  command: uname -r
  register: kernel_release

- name: Install the WireGuard packages
  apt:
    package:
      - wireguard-dkms
      - wireguard-tools
